spring.application.name=backend

# spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/apexledger
spring.datasource.username=apexledger
spring.datasource.password=apexledger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.application.name=backend

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false